### ISSUE TITLE
When trying to upload an album this error appears

### ISSUE THREAD

**Issue by Riscky** [svsticky/pxl#67]
```
Creating new album.
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    cli.main()
  File "/home/rick/projects/itcrowd/pxl/pxl/cli.py", line 278, in main
    cli()
  File "/home/rick/.local/share/virtualenvs/pxl--gtXNr_R/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/rick/.local/share/virtualenvs/pxl--gtXNr_R/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/rick/.local/share/virtualenvs/pxl--gtXNr_R/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rick/.local/share/virtualenvs/pxl--gtXNr_R/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rick/.local/share/virtualenvs/pxl--gtXNr_R/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/rick/projects/itcrowd/pxl/pxl/cli.py", line 134, in upload_cmd
    image = upload.public_image_with_size(client, entry)
  File "/home/rick/projects/itcrowd/pxl/pxl/upload.py", line 109, in public_image_with_size
    local_scaled_files = compress.compress_image(local_filename)
  File "/home/rick/projects/itcrowd/pxl/pxl/compress.py", line 24, in compress_image
    image = image.convert("RGB")
AttributeError: 'NoneType' object has no attribute 'convert'

```

**Comment by Riscky** [comment]
Problem was a weird exif orientation tag. Issue is fixed in b457a0
